Fix for AttributeError: module 'xman.platform' has no attribute 'check_jupyter_notebook_kernel_interrupted'
(cherry picked from commit 020ff68b809f107fbaa849b85c06977c569d5466)